### ISSUE TITLE
My question

### ISSUE THREAD

**Issue by libaipeng1314** [pikaju/flutter-braintree#104]
firebase_auth: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "flutter_braintree":
  In Podfile:
    flutter_braintree (from `.symlinks/plugins/flutter_braintree/ios`)

Specs satisfying the `flutter_braintree (from `.symlinks/plugins/flutter_braintree/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by pikaju** [comment]
Please try the latest version and reopen if the issue persists.
