### ISSUE TITLE
App crashed when clicked 'Proceed with sandbox purchase' 

### ISSUE THREAD

**Issue by gopalindians** [pikaju/flutter-braintree#11]
flutter doctor v`

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/gopal/Downloads/flutter_linux_v0.9.4-beta/flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/gopal/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/gopal/Android/Sdk
    • Java binary at: /snap/android-studio/81/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/81/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /home/gopal/डाउनलोड/ideaIU-2019.1.3/idea-IU-191.7479.19
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Redmi Note 7 Pro • f185687c • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category

**Comment by Pikaju** [comment]
Did it print any stack traces while crashing?

**Comment by gopalindians** [comment]
Its just saying `Lost connection to device.`
![Screenshot from 2020-01-11 19-47-40](https://user-images.githubusercontent.com/1937433/72205632-64001380-34ab-11ea-9297-589d96b3ae87.png)

**Comment by pauli2406** [comment]
Same problem for me. Any information regarding a fix?
