### ISSUE TITLE
Safety

### ISSUE THREAD

**Issue by johannmachemer** [pikaju/flutter-braintree#114]
Hello everyone,
i have a question about the safety of the flutter-braintree plugin. 
I want to use it for a Marketplace app and i am asking myself if it is safe to use in terms of scam and privacy of the credit card information.

I would be very grateful if you can give me an answer.

Kind regards and thanks in advice

**Comment by pikaju** [comment]
Hey, the plugin itself doesn't store any credit card details or anything, it is just a wrapper around the official Braintree Mobile SDKs. Braintree (owned by PayPal) securely stores everything. I would trust PayPal a lot more in terms of security than myself, so you should be fine.
