### ISSUE TITLE
3D verification option not applied

### ISSUE THREAD

**Issue by sharpsan** [pikaju/flutter-braintree#120]
When BraintreeDropInRequest has a non-null `amount`, `requestThreeDSecureVerification` is not applied.  This results in 3D verification being enforced.  I only caught this because I migrated from an older version of this library and did not notice that `amount` is specifically for 3D verification, and I struggled to figure out why I could not turn it off.

**Comment by pikaju** [comment]
Hey, please try version `4.0.0-dev.1` with the `billingAddress` field explained at the bottom of the README.
