### ISSUE TITLE
How will this package manage the transition to 3DS 2.0

### ISSUE THREAD

**Issue by nicolobozzato** [pikaju/flutter-braintree#125]
I received a message that reminds me that:

> In mid-October 2022, 3DS 1.0 will be officially deprecated by all major card providers, making EMV 3DS (commonly called 3DS 2.0) the new standard in 3D Secure authentication protocol.
https://www.paypal.com/uk/smarthelp/article/faq4728

Accordingly there are instruction on the braintree website to migrate to this standard:
https://developer.paypal.com/braintree/docs/guides/3d-secure/migration

It seems that the key here is to send as much information as possible about the user (i.e. address etc..) and specify Version 2 of the 3ds but this plugin doesn't implement this part.

Is there a plan or is in program to implement it?
Thanks

**Comment by pikaju** [comment]
As you implemented this successfully, I will close the issue, but we may need a bug issue for the PayPal tokenization. Thank you again.
