### ISSUE TITLE
Endless loading screen when checkout or return in Android

### ISSUE THREAD

**Issue by sekarvetrivel** [pikaju/flutter-braintree#130]
When checking out or returning, the custom tab on Android is unresponsive and displays an endless loading screen.

[pay.webm](https://user-images.githubusercontent.com/105904147/216890827-4405a7fb-174b-413f-a964-ce444f095d69.webm)

[back.webm](https://user-images.githubusercontent.com/105904147/216890726-09b1f520-e952-4ccc-adba-8830772c6659.webm)

**Comment by BunnyBuddy** [comment]
Can you explain if this issue is resolved and how?

**Comment by rajaflutterdev** [comment]
can you explain how to solve that issue
