### ISSUE TITLE
Is there no way to use Hosted Fields with Flutter or any other way to make our payments more secure ? In the documentation it says "Hosted Fields is only available for JavaScript"

### ISSUE THREAD

**Issue by BunnyBuddy** [pikaju/flutter-braintree#132]
I there any other way to make our payments/ payment methods more secure than it is with drop in ?

**Comment by pikaju** [comment]
Hosted fields is a web-only technology, so you can't really use it in a native Android/iOS app. You could however build a website for your payment flow and then redirect from your mobile app to the website.

Why are you worried about security? The Braintree Android/iOS SDKs should be secure enough, right?
