### ISSUE TITLE
I got the exception when I pressed the Paypal on IOS

### ISSUE THREAD

**Issue by chicrock** [pikaju/flutter-braintree#26]
Hi ~ I got the exception below.

![image](https://user-images.githubusercontent.com/1574553/84845328-56b50980-b087-11ea-92d8-a0879e168dbf.png)

It happened when I pressed the Paypal button In DropIn request.

Here is my code.

```dart
var request = BraintreeDropInRequest(
  tokenizationKey: 'my token',
  collectDeviceData: false,
  paypalRequest: BraintreePayPalRequest(
    amount: '3.0',
    currencyCode: 'USD',
    displayName: 'Display',
  ),
);

BraintreeDropInResult result = BraintreeDropIn.start(request);
```

Are any other setups for Paypal in ios ?
Or, how can I set up the One Touch for callback URL ?

**Comment by DriftingShadows** [comment]
I get exactly the same thing. Were there updates on this @Pikaju by any chance?

**Comment by pikaju** [comment]
This issue is very old, please reopen if it still persists in the latest version.
