### ISSUE TITLE
Can't find the payment on dashboard

### ISSUE THREAD

**Issue by Tharaka8999** [pikaju/flutter-braintree#40]
I have run the example code with my Braintree token and got the payment method nonce successfully, but cant find the transaction from Braintree dashboard. please check this.
![Screenshot_1600683481](https://user-images.githubusercontent.com/16105049/93755969-e7b8f500-fc21-11ea-9e81-b8ac17402414.png)

**Comment by pikaju** [comment]
The payment method nonce alone does not complete a transaction. You need a backend server that receives the nonce from your mobile application and then uses the Braintree SDK to actually receive money. Check out the official developer docs from Braintree for more details: https://developers.braintreepayments.com/start/overview
