### ISSUE TITLE
Enquiries about Credit Card CVV

### ISSUE THREAD

**Issue by JinG312** [pikaju/flutter-braintree#41]
Is that way to add CVV on the request?
Or how should I pass in the CreditCard details with CVV?

final request = BraintreeCreditCardRequest(
  cardNumber: '4111111111111111',
  expirationMonth: '12',
  expirationYear: '2021',
);

Thanks in advance

**Comment by pikaju** [comment]
Unfortunately, I believe this isn't supported yet. Pull requests are much appreciated.

**Comment by pikaju** [comment]
Should now be supported in version `1.2.1`.
