### ISSUE TITLE
playstore issue (Vulnerability in plugin)

### ISSUE THREAD

**Issue by Tharaka8999** [pikaju/flutter-braintree#43]
when i submit app to playstore they are reject app by given error (Your app(s) are using an unsafe implementation of the HostnameVerifier interface.)
when i remove this plugin from project playstore accept my project

**Comment by dhpl** [comment]
I also had the same problem, do you have a fix?

**Comment by Tharaka8999** [comment]
nope

**Comment by dhpl** [comment]
I have fixed it, you need to update build gradle braintree 
```
dependencies {
  implementation 'com.braintreepayments.api:drop-in:5.0.1'
}
```

**Comment by Tharaka8999** [comment]
thank you very much

**Comment by matthewp672261** [comment]
@dhpl did you edit the package directly or put this I the app's build.gradle? Thanks for your help!

**Comment by dhpl** [comment]
@matthewp672261 
You can use this fork, I have updated. 
`flutter_braintree:
    git:
      url: https://github.com/dhpl/flutter-braintree.git
      ref: master`

**Comment by pikaju** [comment]
Hey, sorry for the wait, I updated the Braintree dependency in version `1.1.0+1`.

**Comment by DriftingShadows** [comment]
@dhpl hey man sorry I tried using your fork but getting a merger fail error when trying to build. Any ideas on that?
