### ISSUE TITLE
Application does not support One Touch callback URL scheme

### ISSUE THREAD

**Issue by ndenisj** [pikaju/flutter-braintree#47]
Hello,

I implemented Braintree's native drop-in. When I choose PayPal, i get this error message:

"(braintree_error, The operation couldn’t be completed. Application does not support One Touch callback URL scheme, null, null".

What is the "One Touch callback URL scheme"? Can anyone help me?

**Comment by ckcherry23** [comment]
I am facing the same problem. Did you find any solution to this?

**Comment by NSKevin** [comment]
I have the same problem. when I change my URL Types's URL Schemes from xxx to com.xxx.xxx (URL Schemes is the same as identifier) it's fine .......

**Comment by pavelgorbach** [comment]
+1

**Comment by pavelgorbach** [comment]
The same on react-native.
Managed to get it work by following these steps: https://developer.paypal.com/braintree/docs/guides/paypal/client-side/ios/v4#register-a-url-type 

1. In Xcode, click on your project in the Project Navigator and navigate to App Target > Info > URL Types
2. Click [+] to add a new URL type
3. Under URL Schemes, enter your app switch return URL scheme. This scheme must start with your app's Bundle ID and be dedicated to Braintree app switch returns. For example, if the app bundle ID is com.your-company.your-app, then your URL scheme could be com.your-company.your-app.payments.

**Comment by pikaju** [comment]
I hope this is solved, closing for now.
