### ISSUE TITLE
Unhandled Exception: PlatformException

### ISSUE THREAD

**Issue by prabavgts** [pikaju/flutter-braintree#53]
Hello,
when I call the below method 

 var request = BraintreeDropInRequest(
                  tokenizationKey: tokenizationKey,
                  collectDeviceData: true,
                  googlePaymentRequest: BraintreeGooglePaymentRequest(
                    totalPrice: '4.20',
                    currencyCode: 'USD',
                    billingAddressRequired: false,
                  ),
                  paypalRequest: BraintreePayPalRequest(
                    amount: '4.20',
                    displayName: 'Example company',
                  ),
                  cardEnabled: true,
                );
                BraintreeDropInResult result = await BraintreeDropIn.start(request);
                if (result != null) {
                  showNonce(result.paymentMethodNonce);
                }

I got the error below,

Unhandled Exception: PlatformException(error, Unable to find explicit activity class {com.example.flutter_animation/com.braintreepayments.api.dropin.DropInActivity}; have you declared this activity in your AndroidManifest.xml?, null, android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.flutter_animation/com.braintreepayments.api.dropin.DropInActivity}; have you declared this activity in your AndroidManifest.xml?

**Comment by HamzaMuazzam** [comment]
did you find the solution ? if yes please guide me.

**Comment by raviEbizz** [comment]
@PrabavathiKalidoss @HamzaMuazzam  you get any solution?

**Comment by raviEbizz** [comment]
<activity android:name="com.example.flutter_braintree.FlutterBraintreeCustom" android:theme="@style/Theme.AppCompat.NoActionBar"/>


add also in this in your AndroidManifest.xml

**Comment by phanvankhai98** [comment]
In File Manifest if you have tools:node="replace" in application, replace it by tools:replace="android:label".
And in 
![Screen Shot 2021-05-26 at 5 50 15 PM](https://user-images.githubusercontent.com/38104664/119647748-d9734680-be4a-11eb-9c8b-8d650ae6c31b.png)

I replace ${applicationId} by appID Ex: your AppID com.example.app_example remove all symbol '_'  = com.example.appexample.braintree

It work for me!

**Comment by emran92** [comment]
> In File Manifest if you have tools:node="replace" in application, replace it by tools:replace="android:label".

Where did you write this? Can you please show? thanks.

**Comment by 4uzhoy** [comment]
For future visitors: 
add tools into your manifest tag
```xml
<manifest
        xmlns:tools="http://schemas.android.com/tools"
        xmlns:android="http://schemas.android.com/apk/res/android"
        package="your.package.name">
```
then input in application tag  replace tool
```xml
 <application
            tools:replace="android:label"
```

after that add braintree activity 

```xml
  <activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
                  android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="${applicationId}.braintree" />
            </intent-filter>
        </activity>
```

**Comment by pikaju** [comment]
I think this is an alternative solution to the one provided in the README. If you think this should be fixed by the plugin itself, please let me konw.
