### ISSUE TITLE
Can't change the language

### ISSUE THREAD

**Issue by JeremyRubioDubois** [pikaju/flutter-braintree#54]
After some researches, I found that it should be possible to have the [Braintree Drop-in UI in 23 langages](https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/javascript/v3#select-a-supported-language-for-your-checkout-form)

But I don't see any params that allow me that manage locale or language etc.

Is there any way for me to achieve to have the Braintree Drop-in UI in French ?

Thanks a lot, 

Jeremy

**Comment by nicolobozzato** [comment]
Did you succeed to find any workaround to this?

**Comment by pikaju** [comment]
I couldn't find documentation from Braintree, I'm assuming they just use the Android OS language.
