### ISSUE TITLE
iOS Error Build

### ISSUE THREAD

**Issue by Zeeshan90** [pikaju/flutter-braintree#61]
Hi, i'm getting this error can you please help me to get through this issue.
'unarchiveObjectWithData:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead

**Comment by yelkamel** [comment]
same here

**Comment by Zeeshan90** [comment]
Did you find any solution for this ? @yelkamel

**Comment by yelkamel** [comment]
Non I didn't sorry, I hope @pikaju will help

**Comment by bennibau** [comment]
you can use my repo until my pr is merged. I upgraded the deps.
https://github.com/pikaju/flutter-braintree/pull/65

**Comment by achalkias** [comment]
Same problem. This should be fixed otherwise the whole plugin is unusable.

**Comment by bennibau** [comment]
Did you try my fork?

**Comment by achalkias** [comment]
Yes and it works. Thank you very much.

**Comment by pikaju** [comment]
Thank you @bennibau, the newest version `2.0.0` should include this fix, please let me know if it works. Thank you for your patience.
