### ISSUE TITLE
Build Failed in iOS release

### ISSUE THREAD

**Issue by cyuket** [pikaju/flutter-braintree#69]
Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_BTApplePayClient

Undefined symbol: _OBJC_CLASS_$_BTDropInRequest

Undefined symbol: _OBJC_CLASS_$_BTThreeDSecureRequest

Undefined symbol: _OBJC_CLASS_$_BTPayPalDriver

Undefined symbol: _OBJC_CLASS_$_BTDropInController

Undefined symbol: _OBJC_CLASS_$_BTCard

Undefined symbol: _OBJC_CLASS_$_BTCardClient

Undefined symbol: _OBJC_CLASS_$_BTPayPalRequest

Undefined symbol: _OBJC_CLASS_$_BTAPIClient

**Comment by pikaju** [comment]
Please try out the new version `2.0.0` and let me know if this fixes your issue. Thank you for your patience.
