### ISSUE TITLE
Failed : Build failed, Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1.

### ISSUE THREAD

**Issue by hacmak18** [pikaju/flutter-braintree#76]
Whenever i run application, application failed with following details:

Launching lib/main.dart on sdk gphone x86 64 arm64 in debug mode...
lib/main.dart:1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1.
     Required by:
         project :app > project :flutter_braintree > com.braintreepayments.api:drop-in:5.2.0 > com.braintreepayments.api:three-d-secure:3.15.0
      > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1.
         > Could not get resource 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.4-1/cardinalmobilesdk-2.2.4-1.pom'.
            > Could not GET 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.4-1/cardinalmobilesdk-2.2.4-1.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by andesappal** [comment]
https://github.com/pikaju/flutter-braintree/issues/74#issuecomment-882661183

**Comment by hacmak18** [comment]
Hey @andesappal 
after adding meven now i am facing this issue : 
Launching lib/main.dart on sdk gphone x86 64 arm64 in debug mode...
lib/main.dart:1
WARNING: [Processor] Library '/home/pc-27/.gradle/caches/modules-2/files-2.1/com.braintreepayments.api/data-collector/4.3.0/7c7529e109c7b0bcb398d2e71789e8491fd38aab/data-collector-4.3.0.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/annotation/NonNull'
 Example of support library reference: 'android/support/annotation/NonNull'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_braintree:generateDebugRFile'.
> Could not resolve all files for configuration ':flutter_braintree:debugCompileClasspath'.
   > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1.
     Required by:
         project :flutter_braintree > com.braintreepayments.api:three-d-secure:3.15.0
      > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1.
         > Could not get resource 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.4-1/cardinalmobilesdk-2.2.4-1.pom'.
            > Could not HEAD 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.4-1/cardinalmobilesdk-2.2.4-1.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 51s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin flutter_braintree...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/home/pc-27/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_braintree-1.2.1/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
2

Exception: The plugin flutter_braintree could not be built due to the issue above.
Exited (sigterm)

**Comment by andesappal** [comment]
Hi @hacmak18. Did you add Maven at cache.dart in the External Library directory?

**Comment by hacmak18** [comment]
No. i added that in my projects app level gradle

**Comment by pikaju** [comment]
Please try out the new version `2.0.0` and let me know if this fixes your issue. Thank you for your patience.
