### ISSUE TITLE
No Transaction history on sandbox

### ISSUE THREAD

**Issue by naumanahmed19** [pikaju/flutter-braintree#84]
Hi,

I am getting` result.nonce` with valid information but when I check the sandbox transactions I don't see any payments, I have enabled paypal.

**Comment by pikaju** [comment]
The nonce itself does not complete the payment. You need to set up a backend, send the nonce there, and from there complete the payment using the Braintree API. See the [Braintree Docs](https://developer.paypal.com/braintree/docs/start/overview) for more details.
