### ISSUE TITLE
CocoaPods could not find compatible versions for pod "flutter_braintree":

### ISSUE THREAD

**Issue by HuskyFly** [pikaju/flutter-braintree#85]
CocoaPods could not find compatible versions for pod "flutter_braintree":
      In Podfile:
        flutter_braintree (from `.symlinks/plugins/flutter_braintree/ios`)

    Specs satisfying the `flutter_braintree (from `.symlinks/plugins/flutter_braintree/ios`)` dependency were found,
    but they required a higher minimum deployment target.

I use flutter_braintree: ^2.0.0+1 and platform :ios, '10.0' But there's still the problem，What should I do?

**Comment by HuskyFly** [comment]
> CocoaPods could not find compatible versions for pod "flutter_braintree":
> In Podfile:
> flutter_braintree (from `.symlinks/plugins/flutter_braintree/ios`)
> 
> ```
> Specs satisfying the `flutter_braintree (from `.symlinks/plugins/flutter_braintree/ios`)` dependency were found,
> but they required a higher minimum deployment target.
> ```
> 
> I use flutter_braintree: ^2.0.0+1 and platform :ios, '10.0' But there's still the problem，What should I do?

I have found the problem，platform :ios, '10.0' is incorrect and should be used platform :ios, '12.0' at least

**Comment by akabisdev** [comment]
Please update that in pub.dev doc also.. Thanks
