### ISSUE TITLE
App Name change to (secure checkout)

### ISSUE THREAD

**Issue by ahmad22aot** [pikaju/flutter-braintree#86]
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.cleanx">

    
    <application
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name="io.flutter.embedding.android.FlutterActivity"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="com.example.cleanx.braintree" />
            </intent-filter>
        </activity>

        <meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true"/>

        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
`

**Comment by Babwenbiber** [comment]
@ahmad22aot how did you solve this?
