### ISSUE TITLE
Need help understanding NOUNCES

### ISSUE THREAD

**Issue by officialFlutterDeveloper** [pikaju/flutter-braintree#88]
ill make it simple and straightforward once I get my nounce id  does that mean my transaction has been completed 100%? or do I need to send nounce anywhere after? also what is nounce

To add one more thing even tho im able to get nounceID the transactions are not showing in Braintree or PayPal sandbox account : /

**Comment by pikaju** [comment]
You need to send the nonce to your backend and then complete the payment flow from there. Please consult the Braintree Developer Docs for more details: https://developer.paypal.com/braintree/docs/start/overview

**Comment by officialFlutterDeveloper** [comment]
I’m very confused there is literally no video or documentation to explain the process after even in the Boring show the video ends at nounce where am I supposed to get flutter related instruction for complete process
