### ISSUE TITLE
Merchant account not found

### ISSUE THREAD

**Issue by luckymehndiratta** [pikaju/flutter-braintree#9]
After attach Key the error show to me 
Unhandled Exception: PlatformException(braintree_error, Merchant account not found, null)

**Comment by Pikaju** [comment]
I believe this may not be a plugin specific error. Please check if you set up your Braintree account and backend correctly. This might help: https://stackoverflow.com/questions/41757631/paypal-with-braintree-saying-merchant-account-not-found

**Comment by tandacedric** [comment]
![image](https://user-images.githubusercontent.com/13773515/100095684-29049580-2e5b-11eb-80ff-f4fae35edf11.png)
Go to the paypal settings and complete the required paypal keys

**Comment by pikaju** [comment]
Looks like this is solved.
